server:
  port: 3344
spring:
  application:
    name: cloud-config-center-server #注册到eureka的访问名称
  cloud:
    config:
      server:
        git:
          #采用shh公钥的方式连接git
          uri: git@github.com:lky5645/springcloud-parent-config.git
          ignoreLocalSshSettings: true  #为了激活基于属性的SSH配置
          #搜索在git上面的项目目录
          search-paths:
            - springcloud-parent-config
      #读取对应的分支
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

