server:
  port: 8008
spring:
  application:
    name: provider-hystrix-order-service
logging:
  file:
    path: log/
    name: cloud-provider-hystrix-order.log
  level:
    org.springfromework.web: debug
eureka:
  client:
    #true表示把自己注册到seever中
    register-with-eureka: true
    #true 才能使用负载均衡ribbon调用
    fetch-registry: true
    service-url:
    #设置交互地址 #单机版
      defaultZone: http://localhost:7001/eureka/
#开启feign客户端支持hystrix
feign:
  hystrix:
    enabled: true

