server:
  port: 8004
spring:
  application:
    name: provider-consul-payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cloud202003?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  #####################采用consul作为注册中心
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.ts.provider.bo
logging:
  file:
    name: cloud-provider-payment.log
    path: log/
  level:
    org.springfromework.web: debug
