server:
  port: 8009
spring:
  application:
    name: provider-zipkin-payment-service
  #配置zipkin用于链路追踪
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
    #采样率介于0到1之间 1表示全部采集
      probability: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cloud202003?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.ts.provider.bo
logging:
  file:
    name: cloud-provider-payment.log
    path: log/
  level:
    org.springfromework.web: debug
eureka:
  client:
    #true表示把自己注册到seever中
    register-with-eureka: true
    #true
    fetch-registry: true
    service-url:
    #设置交互地址 单机版
      defaultZone: http://localhost:7001/eureka/
  instance:
  #主机名的修改
    instance-id: zipkinPayment8009
    #访问路径可以显示ip地址
    prefer-ip-address: true